project:
  type: website
  output-dir: docs

website:
  title: "Spotify Analysis HAX712X"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis.qmd
        text: Music Analysis